
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_USER: arthur123          
      MYSQL_PASSWORD: 123456        
      MYSQL_DATABASE: diplomas     # nome do banco de dados
      MYSQL_ROOT_PASSWORD: root123 
    ports:
      - "3306:3306"                # porta MySQL
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
      - db_data:/var/lib/mysql  # Named volume for MySQL data


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"                
      - "15672:15672"             
  redis:
    image: redis:latest
    ports:
      - "6379:6379"                

  api:
    build: ./api
    ports:
      - "5000:5000"                # porta para a API
    depends_on:
      - database
      - rabbitmq
      - redis

  worker:
    build: ./worker
    depends_on:
      - database
      - rabbitmq

volumes:
  db_data: