version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: diplomas
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # porta para conexão
      - "15672:15672" # porta para interface de administração

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - database
      - rabbitmq
      - redis

  worker:
    build: ./worker
    depends_on:
      - database
      - rabbitmq
